services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo_db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - odoo

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    networks:
      - odoo
    volumes:
      - ./odoo.conf:/etc/odoo.conf
    command: ["odoo", "-i", "base", "--config=/etc/odoo.conf"]

networks:
  odoo:   
    driver: bridge